In [4]:
from sklearn.linear_model import LinearRegression
import numpy as np

In [5]:
X = np.array([[1,1],[1,2],[2,2],[2,3]])

In [8]:
y = np.dot(X, np.array([1,2])) + 3

In [9]:
reg = LinearRegression().fit(X,y)

In [13]:
reg.predict(np.array([[3,5]]))

array([16.])

In [15]:
reg.predict(np.array([[1,2],[2,3],[2,3],[3,4]]))

array([ 8., 11., 11., 14.])

In [23]:
import sklearn
print('sklearn: {}'.format(sklearn.__version__))

sklearn: 0.20.1


In [25]:
B1 = reg.coef_
B1

array([1., 2.])

In [27]:
B0 = reg.intercept_
B0

3.000000000000001